export enum MessageFromBack {
  GET_CHAT = "GET_CHAT",
  ADD_MESSAGE = "ADD_MESSAGE",
  START_WRITING = "START_WRITING",
  END_WRITING = "END_WRITING",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  NEW_CHAT = "NEW_CHAT",
  CHANGE_MESSAGE = "CHANGE_MESSAGE",
  ERROR = "ERROR",
  START = "START",
}
